### ISSUE TITLE
Fatal error reading xml file

### ISSUE THREAD

**Issue by angelbonet** [adriannier/eruption#4]
After "erupt" command execution as the instructions says, I've received an error message.

`Fatal error: Uncaught Exception: Cannot read file at /Users/userAccount/Desktop/origen/VC.xml because source files of type text/xml are not supported. in /Users/userAccount/Documents/Desarrollo/eruption-master/functions/utilities.php:25
Stack trace:
#0 /Users/userAccount/Documents/Desarrollo/eruption-master/classes/FMXMLProcessor.php(36): throwError('Cannot read fil...')
#1 /Users/userAccount/Documents/Desarrollo/eruption-master/classes/FMXMLProcessor.php(18): FMXMLProcessor->setSourceFile('/Users/userAcco...')
#2 /Users/userAccount/Documents/Desarrollo/eruption-master/erupt(30): FMXMLProcessor->__construct('/Users/userAcco...', '/Users/userAcco...')
#3 {main}
  thrown in /Users/userAccount/Documents/Desarrollo/eruption-master/functions/utilities.php on line 25`

without any other result.

**Comment by adriannier** [comment]
Thank you for reporting this bug. I added text/xml to the supported mime types.
